"env": "local"
"Service":
  "Name": "SSO"
  "Host": "127.0.0.1"
  "Port": "8000"
  "AllowedHost": "http://127.0.0.1"
  "AllowedPort": "8000"
"Metrics":
  "Port": "9000"
Postgres:
  Host: "localhost"
  Port: "5432"
  DBName: "postgres"
  User: "postgres"
  Password: "postgres"
  SSLMode: "disable"
  PGDriver: "pgx"
  MaxOpenConns: 60
  ConnMaxLifetime: 120s
  MaxIdleConns: 30
  ConnMaxIdleTime: 20s