"env": "local"
"Service":
  "Name": "SSO"
  "Host": "localhost"
  "Port": "8000"
  "AllowedHost": "http://localhost"
  "AllowedPort": "8000"
"Metrics":
  "Port": "9000"
Postgres:
  Host: "localhost"
  Port: "5432"
  DBName: "postgres"
  User: "postgres"
  Password: "postgres"
  SSLMode: "disable"
  PGDriver: "pgx"
  MaxOpenConns: 60
  ConnMaxLifetime: 120s
  MaxIdleConns: 30
  ConnMaxIdleTime: 20s
Redis:
  Host: "localhost"
  Port: "6379"
  Password: "redis"
  UseCertificates: false
  InsecureSkipVerify: true
  DB: 0
  MinIdleConns: 15
  PoolSize: 10
  PoolTimeout: 30