version: '3'

tasks:
  run:
    desc: "Start program"
    cmds:
     - cd app && go run cmd/sso/main.go
  tidy:
    cmds:
      - cd app && go mod tidy
  migup:
    cmds:
      - cd app && go run cmd/migration/main.go --action up
